---
# Tasks file for ansible-role-dotfiles

- name: Determine home directory for paths.
  set_fact:
    dotfiles_home_dir: "{{  (ansible_os_family == 'Darwin') | ternary('Users', 'home') }}"

- name: Clone and link dotfiles.
  include_tasks: "clone-dotfiles.yml"
  loop: "{{ dotfiles_repos }}"
  loop_control:
    loop_var: dotfiles_repo
