---
# Dotfile symlink tasks for ansible-role-dotfiles.

- name: Determine filename for allowlist checks.
  ansible.builtin.set_fact:
    dotfile_current_file: "{{ dotfiles_repo_path | basename }}"
    dotfile_current_file_parent: "{{ dotfiles_repo_path | replace (dotfiles_config_segment, '') | dirname }}"

- name: Make sure directory and links are present.
  block:
    - name: Ensure directory '{{ dotfile_current_file_parent }}/' exists.
      ansible.builtin.file:
        path: "{{ dotfile_current_file_parent }}"
        owner: "{{ dotfiles_repo.owner }}"
        group: "{{ dotfiles_repo.group }}"
        state: directory
      when: "dotfile_current_file_parent != dotfiles_user_dir"

    - name: Link dotfile '{{ dotfile_current_file }}' into place.
      ansible.builtin.file:
        src: "{{ dotfiles_repo_path }}"
        dest: "{{ dotfiles_repo_path | replace(dotfiles_config_segment, '') }}"
        owner: "{{ dotfiles_repo.owner }}"
        group: "{{ dotfiles_repo.group }}"
        state: link
        force: "{{ dotfiles_repo.force_links | default(false) }}"

  when:
    - "dotfile_current_file != '.git'"
    - >
      ((dotfiles_allowlist | length) and (dotfile_current_file in dotfiles_allowlist))
      or ((not dotfiles_allowlist | length) and (dotfile_current_file not in dotfiles_denylist))
