---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-dotfiles
  vars:
    dotfiles_repos:
      - repo: "https://git@github.com/paulirish/dotfiles.git"
        name: "dotfiles"
        version: "master"
        owner: "molecule-1"
        group: "molecule-1"
        allowlist:
          - ".git"
          - ".gitconfig"
          - ".vimrc"
      - repo: "https://git@github.com/paulirish/dotfiles.git"
        name: "dotfiles"
        version: "master"
        owner: "molecule-2"
        group: "molecule-2"
        allowlist:
          - ".vim"
          - ".zshrc"
      - repo: "https://git@github.com/paulirish/dotfiles.git"
        name: "dotfiles"
        version: "master"
        owner: "molecule-3"
        group: "molecule-3"
        denylist:
          - ".zshrc"
        force_links: true
