---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-dotfiles
  vars:
    dotfiles_owner: "molecule"
    dotfiles_group: "molecule"
    dotfiles_repos:
      - repo: "https://ctorgalson@github.com/paulirish/dotfiles.git"
        user: "molecule-1"
        name: "dotfiles"
        version: "master"
        become_user: "molecule-1"
        whitelist:
          - ".gitconfig"
          - ".vimrc"
      - repo: "https://ctorgalson@github.com/paulirish/dotfiles.git"
        user: "molecule-2"
        name: "dotfiles"
        version: "master"
        become_user: "molecule-2"
        whitelist:
          - ".vim"
          - ".zshrc"
