---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-dotfiles
  vars:
    dotfiles_owner: "molecule"
    dotfiles_group: "molecule"
    dotfiles_whitelist:
      - ".vimrc.after"
      - ".vimrc.before"
      - "konsolerc"
      - "Solarized Dev.profile"
