---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install required packages on host.
      apt:
        name:
          - "git"
        update_cache: true

    - name: Create molecule user for testing.
      user:
        name: "{{ name }}"
      loop:
        - "molecule-1"
        - "molecule-2"
        - "molecule-3"
      loop_control:
        loop_var: name
