---
on: push

jobs:
  molecule:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
      - uses: gofrolist/molecule-action@v2
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
